const Scan = require('../models/Scan');
const geminiService = require('../services/geminiService');

// Save a new scan
exports.saveScan = async (req, res) => {
  try {
    const { 
      userId, 
      imageUrl, 
      prediction, 
      confidence, 
      diseaseInfo, 
      location, 
      notes,
      // New Gemini validation fields
      variety,
      validationStatus,
      aiPrediction,
      // User-editable name
      name
    } = req.body;

    if (!userId || !imageUrl || !prediction || !confidence) {
      return res.status(400).json({ message: 'Missing required fields' });
    }

    const newScan = new Scan({
      userId,
      imageUrl,
      prediction,
      confidence,
      diseaseInfo,
      location,
      notes,
      // Save new validation fields if provided
      variety: variety || null,
      validationStatus: validationStatus || 'tflite_only',
      aiPrediction: aiPrediction || {},
      name: name || '' // Will be auto-generated by pre-save hook if empty
    });

    const savedScan = await newScan.save();

    res.status(201).json({
      message: 'Scan saved successfully',
      scan: savedScan
    });
  } catch (error) {
    console.error('Error saving scan:', error);
    res.status(500).json({ message: 'Server error while saving scan', error: error.message });
  }
};

// Get scan history for a user
exports.getScanHistory = async (req, res) => {
  try {
    const { userId } = req.params;

    if (!userId) {
      return res.status(400).json({ message: 'User ID is required' });
    }

    const scans = await Scan.find({ userId }).sort({ date: -1 });

    res.status(200).json(scans);
  } catch (error) {
    console.error('Error fetching scan history:', error);
    res.status(500).json({ message: 'Server error while fetching history', error: error.message });
  }
};

// Get a single scan by ID
exports.getScanById = async (req, res) => {
  try {
    const { id } = req.params;

    const scan = await Scan.findById(id);

    if (!scan) {
      return res.status(404).json({ message: 'Scan not found' });
    }

    res.status(200).json(scan);
  } catch (error) {
    console.error('Error fetching scan:', error);
    res.status(500).json({ message: 'Server error while fetching scan', error: error.message });
  }
};

// Delete a scan
exports.deleteScan = async (req, res) => {
  try {
    const { id } = req.params;

    const deletedScan = await Scan.findByIdAndDelete(id);

    if (!deletedScan) {
      return res.status(404).json({ message: 'Scan not found' });
    }

    res.status(200).json({ message: 'Scan deleted successfully' });
  } catch (error) {
    console.error('Error deleting scan:', error);
    res.status(500).json({ message: 'Server error while deleting scan', error: error.message });
  }
};

// Update a scan (for editing name, notes, etc.)
exports.updateScan = async (req, res) => {
  try {
    const { id } = req.params;
    const { name, notes } = req.body;

    const updateData = {};
    if (name !== undefined) updateData.name = name;
    if (notes !== undefined) updateData.notes = notes;

    const updatedScan = await Scan.findByIdAndUpdate(
      id,
      updateData,
      { new: true, runValidators: true }
    );

    if (!updatedScan) {
      return res.status(404).json({ message: 'Scan not found' });
    }

    res.status(200).json({ message: 'Scan updated successfully', scan: updatedScan });
  } catch (error) {
    console.error('Error updating scan:', error);
    res.status(500).json({ message: 'Server error while updating scan', error: error.message });
  }
};

// Get harvest prediction from Gemini
exports.getHarvestPrediction = async (req, res) => {
  try {
    const { scanData, environmentalData } = req.body;

    if (!scanData || !scanData.prediction || !scanData.confidence) {
        return res.status(400).json({ message: 'Missing required scan data for prediction' });
    }

    const prediction = await geminiService.generateHarvestPrediction(scanData, environmentalData || {});

    if (prediction.error) {
        return res.status(500).json({ message: prediction.error, details: prediction.details });
    }

    res.status(200).json(prediction);
  } catch (error) {
    console.error('Error getting harvest prediction:', error);
    res.status(500).json({ message: 'Server error while generating prediction', error: error.message });
  }
};

// Analyze image with Gemini (Variety & Gender validation)
exports.analyzeImage = async (req, res) => {
  try {
    const { image, tmPrediction } = req.body;
    
    if (!image) {
      return res.status(400).json({ message: 'Missing image data' });
    }

    // Call service
    const result = await geminiService.analyzeImage(image, tmPrediction);
    
    res.json(result);
  } catch (error) {
    console.error('Error analyzing image:', error);
    res.status(500).json({ 
      message: 'Analysis failed', 
      error: error.message 
    });
  }
};
