import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share
} from 'react-native';
import { theme } from '../../styles';
import { Ionicons } from '@expo/vector-icons';

export const PredictionResultsScreen = ({ navigation, route }) => {
  const { prediction, plant } = route.params;

  const getConfidenceColor = (confidence) => {
    if (confidence >= 80) return theme.colors.success;
    if (confidence >= 60) return theme.colors.warning;
    return theme.colors.error;
  };

  const getImpactIcon = (impact) => {
    switch (impact) {
      case 'positive':
        return { name: 'arrow-up-circle', color: theme.colors.success };
      case 'negative':
        return { name: 'arrow-down-circle', color: theme.colors.error };
      default:
        return { name: 'remove-circle', color: theme.colors.text.secondary };
    }
  };

  const getPriorityColor = (priority) => {
    switch (priority) {
      case 'high':
        return theme.colors.error;
      case 'medium':
        return theme.colors.warning;
      default:
        return theme.colors.text.secondary;
    }
  };

  const handleShare = async () => {
    try {
      const message = `
🌸 Flower Production Prediction 🌸

Plant: ${prediction.plantType}
Age: ${prediction.plantAge} days

📊 Predicted Production:
Male Flowers: ${prediction.maleFlowers.min}-${prediction.maleFlowers.max} (avg: ${prediction.maleFlowers.average})
Female Flowers: ${prediction.femaleFlowers.min}-${prediction.femaleFlowers.max} (avg: ${prediction.femaleFlowers.average})
Total: ${prediction.totalFlowers.min}-${prediction.totalFlowers.max} flowers

Confidence: ${prediction.confidence}%

Generated by eGourd App
      `.trim();

      await Share.share({
        message,
        title: 'Flower Prediction Results'
      });
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  return (
    <View style={styles.container}>
      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        {/* Header with confidence */}
        <View style={styles.header}>
          <View style={styles.confidenceContainer}>
            <Text style={styles.confidenceLabel}>Prediction Confidence</Text>
            <Text style={[
              styles.confidenceValue,
              { color: getConfidenceColor(prediction.confidence) }
            ]}>
              {prediction.confidence}%
            </Text>
            <View style={styles.confidenceBar}>
              <View
                style={[
                  styles.confidenceBarFill,
                  {
                    width: `${prediction.confidence}%`,
                    backgroundColor: getConfidenceColor(prediction.confidence)
                  }
                ]}
              />
            </View>
          </View>
        </View>

        {/* Plant Info */}
        {plant && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Ionicons name="leaf" size={20} color={theme.colors.primary} />
              <Text style={styles.sectionTitle}>Plant Information</Text>
            </View>
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Name:</Text>
              <Text style={styles.infoValue}>{plant.displayName?.english || plant.name}</Text>
            </View>
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Status:</Text>
              <Text style={styles.infoValue}>{plant.status}</Text>
            </View>
          </View>
        )}

        {/* Prediction Results */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="flower" size={20} color={theme.colors.primary} />
            <Text style={styles.sectionTitle}>Predicted Flower Production</Text>
          </View>

          <View style={styles.predictionsGrid}>
            {/* Male Flowers */}
            <View style={[styles.predictionCard, { backgroundColor: '#E3F2FD' }]}>
              <View style={styles.predictionIcon}>
                <Ionicons name="male" size={32} color="#1976D2" />
              </View>
              <Text style={styles.predictionLabel}>Male Flowers</Text>
              <Text style={[styles.predictionValue, { color: '#1976D2' }]}>
                {prediction.maleFlowers.average}
              </Text>
              <Text style={styles.predictionRange}>
                Range: {prediction.maleFlowers.min}-{prediction.maleFlowers.max}
              </Text>
            </View>

            {/* Female Flowers */}
            <View style={[styles.predictionCard, { backgroundColor: '#FCE4EC' }]}>
              <View style={styles.predictionIcon}>
                <Ionicons name="female" size={32} color="#C2185B" />
              </View>
              <Text style={styles.predictionLabel}>Female Flowers</Text>
              <Text style={[styles.predictionValue, { color: '#C2185B' }]}>
                {prediction.femaleFlowers.average}
              </Text>
              <Text style={styles.predictionRange}>
                Range: {prediction.femaleFlowers.min}-{prediction.femaleFlowers.max}
              </Text>
            </View>

            {/* Total Flowers */}
            <View style={[styles.predictionCard, styles.totalCard]}>
              <View style={styles.predictionIcon}>
                <Ionicons name="analytics" size={32} color={theme.colors.primary} />
              </View>
              <Text style={styles.predictionLabel}>Total Flowers</Text>
              <Text style={[styles.predictionValue, { color: theme.colors.primary }]}>
                {prediction.totalFlowers.average}
              </Text>
              <Text style={styles.predictionRange}>
                Range: {prediction.totalFlowers.min}-{prediction.totalFlowers.max}
              </Text>
            </View>
          </View>
        </View>

        {/* Influencing Factors */}
        {prediction.influencingFactors && prediction.influencingFactors.length > 0 && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Ionicons name="information-circle" size={20} color={theme.colors.primary} />
              <Text style={styles.sectionTitle}>Influencing Factors</Text>
            </View>
            {prediction.influencingFactors.map((factor, index) => {
              const icon = getImpactIcon(factor.impact);
              return (
                <View key={index} style={styles.factorItem}>
                  <Ionicons name={icon.name} size={24} color={icon.color} />
                  <View style={styles.factorContent}>
                    <Text style={styles.factorName}>{factor.factor}</Text>
                    <Text style={styles.factorDescription}>{factor.description}</Text>
                  </View>
                </View>
              );
            })}
          </View>
        )}

        {/* Recommendations */}
        {prediction.recommendations && prediction.recommendations.length > 0 && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Ionicons name="bulb" size={20} color={theme.colors.primary} />
              <Text style={styles.sectionTitle}>Recommendations</Text>
            </View>
            <Text style={styles.recommendationsIntro}>
              Follow these tips to improve flower production:
            </Text>
            {prediction.recommendations.map((rec, index) => {
              const priorityColor = getPriorityColor(rec.priority);
              return (
                <View key={index} style={styles.recommendationItem}>
                  <View style={styles.recommendationHeader}>
                    <View style={[styles.priorityDot, { backgroundColor: priorityColor }]} />
                    <Text style={styles.recommendationCategory}>
                      {rec.category.toUpperCase()}
                    </Text>
                    <Text style={[styles.priorityText, { color: priorityColor }]}>
                      {rec.priority}
                    </Text>
                  </View>
                  <Text style={styles.recommendationText}>{rec.suggestion}</Text>
                </View>
              );
            })}
          </View>
        )}

        {/* Action Buttons */}
        <View style={styles.actionsSection}>
          <TouchableOpacity
            style={[styles.actionButton, styles.shareButton]}
            onPress={handleShare}
          >
            <Ionicons name="share-social" size={20} color="#fff" />
            <Text style={styles.actionButtonText}>Share Results</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.actionButton, styles.newPredictionButton]}
            onPress={() => navigation.goBack()}
          >
            <Ionicons name="add-circle" size={20} color={theme.colors.primary} />
            <Text style={[styles.actionButtonText, { color: theme.colors.primary }]}>
              New Prediction
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.actionButton, styles.doneButton]}
            onPress={() => navigation.navigate('Pollination')}
          >
            <Text style={styles.actionButtonText}>Done</Text>
          </TouchableOpacity>
        </View>

        <View style={styles.bottomPadding} />
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.primary,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    backgroundColor: '#fff',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  confidenceContainer: {
    alignItems: 'center',
  },
  confidenceLabel: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    marginBottom: 8,
  },
  confidenceValue: {
    fontSize: 48,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  confidenceBar: {
    width: '100%',
    height: 8,
    backgroundColor: theme.colors.background.primary,
    borderRadius: 4,
    overflow: 'hidden',
  },
  confidenceBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  section: {
    backgroundColor: '#fff',
    marginTop: 16,
    padding: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: theme.colors.border,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginLeft: 8,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  infoLabel: {
    fontSize: 14,
    color: theme.colors.text.secondary,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.text.primary,
  },
  predictionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
  },
  predictionCard: {
    width: '47%',
    margin: 6,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  totalCard: {
    width: '100%',
    backgroundColor: theme.colors.background.secondary,
  },
  predictionIcon: {
    marginBottom: 8,
  },
  predictionLabel: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    marginBottom: 4,
  },
  predictionValue: {
    fontSize: 36,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  predictionRange: {
    fontSize: 12,
    color: theme.colors.text.secondary,
  },
  factorItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  factorContent: {
    flex: 1,
    marginLeft: 12,
  },
  factorName: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginBottom: 4,
  },
  factorDescription: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    lineHeight: 20,
  },
  recommendationsIntro: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    marginBottom: 16,
  },
  recommendationItem: {
    backgroundColor: theme.colors.background.primary,
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  recommendationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  priorityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  recommendationCategory: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.text.secondary,
    flex: 1,
  },
  priorityText: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  recommendationText: {
    fontSize: 14,
    color: theme.colors.text.primary,
    lineHeight: 20,
  },
  actionsSection: {
    marginTop: 16,
    paddingHorizontal: 16,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  shareButton: {
    backgroundColor: theme.colors.secondary,
  },
  newPredictionButton: {
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: theme.colors.primary,
  },
  doneButton: {
    backgroundColor: theme.colors.primary,
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 8,
  },
  bottomPadding: {
    height: 32,
  },
});
