import React from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  Platform,
  Share
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';

const YieldResultsScreen = ({ navigation, route }) => {
  const { t } = useTranslation();
  const { prediction } = route.params;

  const getPlantTypeLabel = (type) => {
    const labels = {
      bitter_gourd: t('predictionForms.plantTypeBitterGourd'),
      bottle_gourd: t('predictionForms.plantTypeBottleGourd'),
      sponge_gourd: t('predictionForms.plantTypeSpongeGourd'),
      cucumber: t('predictionForms.plantTypeCucumber'),
      kalabasa: t('predictionForms.plantTypeSquash')
    };
    return labels[type] || type;
  };

  const getConfidenceColor = (score) => {
    if (score >= 80) return '#4caf50';
    if (score >= 60) return '#ff9800';
    return '#f44336';
  };

  const getConfidenceLabel = (score) => {
    if (score >= 80) return t('predictionResults.highConfidence');
    if (score >= 60) return t('predictionResults.moderateConfidence');
    return t('predictionResults.lowConfidence');
  };

  const handleShare = async () => {
    try {
      const message = `
🌱 Yield Prediction Results

Plant Type: ${getPlantTypeLabel(prediction.prediction.plant_type || prediction.input_summary?.plant_type)}
Predicted Yield: ${prediction.prediction.yield_kg} kg
Confidence: ${prediction.prediction.confidence_score}%

Input Summary:
- Plant Age: ${prediction.input_summary.plant_age_days} days
- Vine Length: ${prediction.input_summary.vine_length_cm} cm
- Node Count: ${prediction.input_summary.node_count}
- Male Flowers: ${prediction.input_summary.male_flower_count}
- Female Flowers: ${prediction.input_summary.female_flower_count}
- Temperature: ${prediction.input_summary.temperature_celsius}°C
- Soil Moisture: ${prediction.input_summary.soil_moisture_percent}%

Generated by PlantCare App
      `.trim();

      await Share.share({
        message
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const plantType = prediction.prediction?.plant_type || prediction.input_summary?.plant_type || 'unknown';
  const yieldKg = prediction.prediction?.yield_kg || 0;
  const confidenceScore = prediction.prediction?.confidence_score || 0;
  const recommendations = prediction.prediction?.recommendations || [];
  const expectedRange = prediction.expected_range || {};

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity 
          style={styles.backButton}
          onPress={() => navigation.navigate('PollinationMain')}
        >
          <Ionicons name="close" size={24} color="#2e7d32" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>{t('predictionResults.yieldResultsTitle')}</Text>
        <TouchableOpacity 
          style={styles.shareButton}
          onPress={handleShare}
        >
          <Ionicons name="share-outline" size={24} color="#2e7d32" />
        </TouchableOpacity>
      </View>

      <ScrollView 
        style={styles.content}
        showsVerticalScrollIndicator={false}
      >
        {/* Main Result Card */}
        <View style={styles.resultCard}>
          <View style={styles.resultHeader}>
            <Ionicons name="leaf" size={32} color="#2e7d32" />
            <Text style={styles.plantTypeText}>
              {getPlantTypeLabel(plantType)}
            </Text>
          </View>

          <View style={styles.yieldContainer}>
            <Text style={styles.yieldLabel}>{t('predictionResults.predictedYield')}</Text>
            <Text style={styles.yieldValue}>{yieldKg}</Text>
            <Text style={styles.yieldUnit}>{t('predictionResults.kilograms')}</Text>
          </View>

          <View style={styles.confidenceContainer}>
            <View style={styles.confidenceHeader}>
              <Ionicons name="checkmark-circle" size={20} color={getConfidenceColor(confidenceScore)} />
              <Text style={styles.confidenceLabel}>{t('predictionResults.confidenceScore')}</Text>
            </View>
            <View style={styles.confidenceBar}>
              <View 
                style={[
                  styles.confidenceFill,
                  { 
                    width: `${confidenceScore}%`,
                    backgroundColor: getConfidenceColor(confidenceScore)
                  }
                ]}
              />
            </View>
            <Text style={[
              styles.confidenceText,
              { color: getConfidenceColor(confidenceScore) }
            ]}>
              {confidenceScore}% - {getConfidenceLabel(confidenceScore)}
            </Text>
          </View>

          {/* Expected Range */}
          {expectedRange.min !== undefined && (
            <View style={styles.rangeContainer}>
              <Text style={styles.rangeTitle}>{t('predictionResults.expectedYieldRange')}</Text>
              <View style={styles.rangeRow}>
                <View style={styles.rangeItem}>
                  <Text style={styles.rangeLabel}>{t('predictionResults.min')}</Text>
                  <Text style={styles.rangeValue}>{expectedRange.min} kg</Text>
                </View>
                <View style={styles.rangeDivider} />
                <View style={styles.rangeItem}>
                  <Text style={styles.rangeLabel}>{t('predictionResults.average')}</Text>
                  <Text style={styles.rangeValue}>{expectedRange.average} kg</Text>
                </View>
                <View style={styles.rangeDivider} />
                <View style={styles.rangeItem}>
                  <Text style={styles.rangeLabel}>{t('predictionResults.max')}</Text>
                  <Text style={styles.rangeValue}>{expectedRange.max} kg</Text>
                </View>
              </View>
            </View>
          )}
        </View>

        {/* Input Summary */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="information-circle-outline" size={24} color="#2e7d32" />
            <Text style={styles.sectionTitle}>{t('predictionResults.inputSummary')}</Text>
          </View>

          <View style={styles.summaryGrid}>
            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>{t('predictionForms.plantAge')}</Text>
              <Text style={styles.summaryValue}>
                {prediction.input_summary.plant_age_days} days
              </Text>
            </View>

            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>{t('predictionForms.vineLength')}</Text>
              <Text style={styles.summaryValue}>
                {prediction.input_summary.vine_length_cm} cm
              </Text>
            </View>

            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>{t('predictionForms.nodeCount')}</Text>
              <Text style={styles.summaryValue}>
                {prediction.input_summary.node_count}
              </Text>
            </View>

            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>{t('predictionForms.maleFlowerCount')}</Text>
              <Text style={styles.summaryValue}>
                {prediction.input_summary.male_flower_count}
              </Text>
            </View>

            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>{t('predictionForms.femaleFlowerCount')}</Text>
              <Text style={styles.summaryValue}>
                {prediction.input_summary.female_flower_count}
              </Text>
            </View>

            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>{t('predictionForms.temperature')}</Text>
              <Text style={styles.summaryValue}>
                {prediction.input_summary.temperature_celsius}°C
              </Text>
            </View>

            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>{t('predictionForms.soilMoisture')}</Text>
              <Text style={styles.summaryValue}>
                {prediction.input_summary.soil_moisture_percent}%
              </Text>
            </View>
          </View>
        </View>

        {/* Recommendations */}
        {recommendations.length > 0 && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Ionicons name="bulb-outline" size={24} color="#2e7d32" />
              <Text style={styles.sectionTitle}>{t('predictionResults.recommendations')}</Text>
            </View>

            {recommendations.map((recommendation, index) => (
              <View key={index} style={styles.recommendationItem}>
                <View style={styles.recommendationBullet} />
                <Text style={styles.recommendationText}>{recommendation}</Text>
              </View>
            ))}
          </View>
        )}

        {/* Model Info */}
        {prediction.model_info && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Ionicons name="analytics-outline" size={24} color="#666" />
              <Text style={styles.sectionTitle}>{t('predictionResults.modelInfo')}</Text>
            </View>

            <View style={styles.modelInfo}>
              {prediction.model_info.test_r2 && (
                <View style={styles.modelInfoRow}>
                  <Text style={styles.modelInfoLabel}>{t('predictionResults.modelAccuracy')}:</Text>
                  <Text style={styles.modelInfoValue}>
                    {(prediction.model_info.test_r2 * 100).toFixed(1)}%
                  </Text>
                </View>
              )}
              {prediction.model_info.test_mae && (
                <View style={styles.modelInfoRow}>
                  <Text style={styles.modelInfoLabel}>{t('predictionResults.averageError')}:</Text>
                  <Text style={styles.modelInfoValue}>
                    ±{prediction.model_info.test_mae.toFixed(2)} kg
                  </Text>
                </View>
              )}
            </View>
          </View>
        )}

        {/* Action Buttons */}
        <View style={styles.actionButtons}>
          <TouchableOpacity
            style={styles.secondaryButton}
            onPress={() => navigation.navigate('PredictYield')}
          >
            <Ionicons name="refresh-outline" size={20} color="#2e7d32" />
            <Text style={styles.secondaryButtonText}>{t('predictionResults.newPrediction')}</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.primaryButton}
            onPress={() => navigation.navigate('PollinationMain')}
          >
            <Ionicons name="checkmark-outline" size={20} color="#fff" />
            <Text style={styles.primaryButtonText}>{t('common.done')}</Text>
          </TouchableOpacity>
        </View>

        <View style={{ height: 30 }} />
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5'
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    ...Platform.select({
      ios: {
        paddingTop: 50
      },
      android: {
        paddingTop: 16
      }
    })
  },
  backButton: {
    padding: 8
  },
  shareButton: {
    padding: 8
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2e7d32',
    flex: 1,
    textAlign: 'center'
  },
  content: {
    flex: 1
  },
  resultCard: {
    backgroundColor: '#fff',
    margin: 16,
    padding: 20,
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4
  },
  resultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20
  },
  plantTypeText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2e7d32',
    marginLeft: 12
  },
  yieldContainer: {
    alignItems: 'center',
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    marginBottom: 20
  },
  yieldLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8
  },
  yieldValue: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#2e7d32'
  },
  yieldUnit: {
    fontSize: 16,
    color: '#666',
    marginTop: 4
  },
  confidenceContainer: {
    marginBottom: 20
  },
  confidenceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8
  },
  confidenceLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginLeft: 8
  },
  confidenceBar: {
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 8
  },
  confidenceFill: {
    height: '100%',
    borderRadius: 4
  },
  confidenceText: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center'
  },
  rangeContainer: {
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0'
  },
  rangeTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
    textAlign: 'center'
  },
  rangeRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center'
  },
  rangeItem: {
    alignItems: 'center',
    flex: 1
  },
  rangeDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#e0e0e0'
  },
  rangeLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4
  },
  rangeValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2e7d32'
  },
  section: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 16,
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginLeft: 8
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8
  },
  summaryItem: {
    width: '50%',
    padding: 8
  },
  summaryLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333'
  },
  recommendationItem: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingLeft: 8
  },
  recommendationBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#2e7d32',
    marginTop: 6,
    marginRight: 12
  },
  recommendationText: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    lineHeight: 20
  },
  modelInfo: {
    backgroundColor: '#f5f5f5',
    padding: 12,
    borderRadius: 8
  },
  modelInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8
  },
  modelInfoLabel: {
    fontSize: 13,
    color: '#666'
  },
  modelInfoValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333'
  },
  actionButtons: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 12
  },
  primaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2e7d32',
    padding: 16,
    borderRadius: 8
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8
  },
  secondaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2e7d32'
  },
  secondaryButtonText: {
    color: '#2e7d32',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8
  }
});

export default YieldResultsScreen;
